// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Swate")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("Version","v1.0.0-beta.13")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","16.10.2024")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Swate"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_Version = "v1.0.0-beta.13"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "16.10.2024"
