version: 2
updates:
  # Daily updates for NuGet packages
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    groups:
      DataPLANT:
        patterns:
          - "ARCtrl*"

  # Weekly updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
