// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Swate")>]
[<assembly: AssemblyVersionAttribute("0.6.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","08.03.2022")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Swate"
    let [<Literal>] AssemblyVersion = "0.6.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "08.03.2022"
