// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Swate")>]
[<assembly: AssemblyVersionAttribute("0.5.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","14-Dec-21")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Swate"
    let [<Literal>] AssemblyVersion = "0.5.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "14-Dec-21"
