[<AutoOpen>]
module ARCtrl.DataMapExtensions

open ARCtrl
open Swate.Components
open Helper
open ArcTableAux

[<RequireQualifiedAccess>]
module DataMapIndices =

    [<Literal>]
    let Data = 0

    [<Literal>]
    let Label = 1

    [<Literal>]
    let Description = 2

    [<Literal>]
    let GeneratedBy = 3

    [<Literal>]
    let Explication = 4

    [<Literal>]
    let Unit = 5

    [<Literal>]
    let ObjectType = 6

type DataMap with

    member this.GetCell(columnIndex: int, rowIndex: int) =
        let r = this.DataContexts.[rowIndex]

        match columnIndex with
        | DataMapIndices.Data -> CompositeCell.createData r
        | DataMapIndices.Label -> doptstr r.Label |> CompositeCell.FreeText
        | DataMapIndices.Description -> doptstr r.Description |> CompositeCell.FreeText
        | DataMapIndices.GeneratedBy -> doptstr r.GeneratedBy |> CompositeCell.FreeText
        | DataMapIndices.Explication ->
            r.Explication
            |> Option.defaultValue (OntologyAnnotation())
            |> CompositeCell.Term
        | DataMapIndices.Unit -> r.Unit |> Option.defaultValue (OntologyAnnotation()) |> CompositeCell.Term
        | DataMapIndices.ObjectType ->
            r.ObjectType |> Option.defaultValue (OntologyAnnotation()) |> CompositeCell.Term
        | i -> failwithf "Invalid column index for DataMap: %i" i


    member this.SetCell(columnIndex: int, rowIndex: int, cell: CompositeCell) =
        let r = this.DataContexts.[rowIndex]

        match columnIndex with
        | DataMapIndices.Data ->
            let nd = cell.AsData
            r.FilePath <- nd.FilePath
            r.Selector <- nd.Selector
            r.Format <- nd.Format
            r.SelectorFormat <- nd.SelectorFormat
        | DataMapIndices.Label -> r.Label <- Some cell.AsFreeText
        | DataMapIndices.Description -> r.Description <- Some cell.AsFreeText
        | DataMapIndices.GeneratedBy -> r.GeneratedBy <- Some cell.AsFreeText
        | DataMapIndices.Explication -> r.Explication <- Some cell.AsTerm
        | DataMapIndices.Unit -> r.Unit <- Some cell.AsTerm
        | DataMapIndices.ObjectType -> r.ObjectType <- Some cell.AsTerm
        | i -> failwithf "Invalid column index for DataMap: %i" i

    static member getHeader(columnIndex: int) =
        match columnIndex with
        | DataMapIndices.Data -> CompositeHeader.Input IOType.Data
        | DataMapIndices.Label -> CompositeHeader.FreeText "Label"
        | DataMapIndices.Description -> CompositeHeader.FreeText "Description"
        | DataMapIndices.GeneratedBy -> CompositeHeader.FreeText "Generated By"
        | DataMapIndices.Explication -> CompositeHeader.Parameter(TermCollection.Explication)
        | DataMapIndices.Unit -> CompositeHeader.Parameter(TermCollection.Unit)
        | DataMapIndices.ObjectType -> CompositeHeader.Parameter(TermCollection.ObjectType)
        | i -> failwithf "Invalid column index for DataMap: %i" i

    member this.Clear(columnIndex: int, rowIndex: int) =
        let r = this.DataContexts.[rowIndex]

        match columnIndex with
        | DataMapIndices.Data ->
            r.FilePath <- None
            r.Selector <- None
            r.Format <- None
            r.SelectorFormat <- None
        | DataMapIndices.Label -> r.Label <- None
        | DataMapIndices.Description -> r.Description <- None
        | DataMapIndices.GeneratedBy -> r.GeneratedBy <- None
        | DataMapIndices.Explication -> r.Explication <- None
        | DataMapIndices.Unit -> r.Unit <- None
        | DataMapIndices.ObjectType -> r.ObjectType <- None
        | i -> failwithf "Invalid column index for DataMap: %i" i
    member this.GetHeader(columnIndex: int) = DataMap.getHeader (columnIndex)

    static member ColumnCount = 7
    member this.ColumnCount = DataMap.ColumnCount
    member this.RowCount = this.DataContexts.Count