name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["Type: Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: why
    attributes:
      label: Is your feature request related to a problem?
      description: This should explain what your goal is you are trying to achieve.
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: suggestion
    attributes:
      label: Describe the solution you would like!
      description: A clear and concise description of what you want to happen.
  - type: dropdown
    id: swate-host
    attributes:
      label: Host
      description: Where did you run Swate?
      options:
        - Applies to All
        - Standalone
        - ARCitect
        - Excel
      default: 0
  - type: textarea
    id: swate-host-details
    attributes:
      label: Host Details
      description: Please give us more information.
      placeholder: |
        Excel
            * Excel version
            * OS [e.g. Windows 11]
        ARCitect
            * ARCitect version
            * OS [e.g. Windows 11]
        Standalone
            * Browser [e.g. Firefox, Chrome]
