USE [master]
GO

/****** Object:  Database [AnnotatorTest]    Script Date: 6/17/2020 2:13:36 PM ******/
CREATE DATABASE [AnnotatorTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AnnotatorTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AnnotatorTest.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AnnotatorTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AnnotatorTest_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AnnotatorTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AnnotatorTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AnnotatorTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AnnotatorTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AnnotatorTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AnnotatorTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [AnnotatorTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AnnotatorTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AnnotatorTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AnnotatorTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AnnotatorTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AnnotatorTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AnnotatorTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AnnotatorTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AnnotatorTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AnnotatorTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AnnotatorTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AnnotatorTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AnnotatorTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AnnotatorTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AnnotatorTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AnnotatorTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AnnotatorTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AnnotatorTest] SET RECOVERY FULL 
GO

ALTER DATABASE [AnnotatorTest] SET  MULTI_USER 
GO

ALTER DATABASE [AnnotatorTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AnnotatorTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AnnotatorTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AnnotatorTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AnnotatorTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AnnotatorTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AnnotatorTest] SET  READ_WRITE 
GO

