// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ISA.Spreadsheet")>]
[<assembly: AssemblyProductAttribute("ISA")>]
[<assembly: AssemblyDescriptionAttribute("ISA compliant experimental metadata toolkit in F#")>]
[<assembly: AssemblyVersionAttribute("0.0.4")>]
[<assembly: AssemblyFileVersionAttribute("0.0.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ISA.Spreadsheet"
    let [<Literal>] AssemblyProduct = "ISA"
    let [<Literal>] AssemblyDescription = "ISA compliant experimental metadata toolkit in F#"
    let [<Literal>] AssemblyVersion = "0.0.4"
    let [<Literal>] AssemblyFileVersion = "0.0.4"
    let [<Literal>] AssemblyConfiguration = "Release"
