# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  workflow_dispatch: # Allows manual runs from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: windows-latest
    # Job steps
    steps:

      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      # Restore .NET tools
      - name: Restore .NET dependencies
        run: dotnet tool restore

      - name: Install root NPM Dependencies
        run: npm install

      # Install dependencies
      - name: Install npm dependencies
        run: npm install
        working-directory: src/Components

      # Build the project
      - name: Build
        run: npm run build:storybook
        working-directory: src/Components

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: echo "install skipped"  # default: npm ci
          build_command: echo "build skipped" # default: npm run build-storybook
          path: src/Components/storybook-static # default: dist/storybook
          checkout: false # default: true