name: Publish Nightly NuGet Package

on:
  push:
    branches: ['nightly', 'gh-action-test-branch']  # Only runs on pushes to the 'nightly' branch
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Extract Latest Tag as Version
        id: get_version
        run: echo "PACKAGE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Restore Dependencies
        run: dotnet restore src/Components/src/Components.fsproj

      - name: Install NPM Dependencies
        run: npm install
        working-directory: src/Components

      - name: Run Prebuild Script
        run: npm run prebuild:net
        working-directory: src/Components

      - name: Build Project
        run: dotnet build src/Components/src/Components.fsproj --configuration Release /p:PackageVersion=${PACKAGE_VERSION}

      - name: Pack NuGet Package
        run: dotnet pack src/Components/src/Components.fsproj --configuration Release --output nupkgs /p:PackageVersion=${PACKAGE_VERSION}

      # - name: Publish to NuGet
      #   run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
