name: Release Swate Electron App
on:
  workflow_dispatch:
  push:
    branches:
      - epic/SwateApp

permissions:
  contents: write

jobs:
  # # --- Job 1: Run tests ---
  # test:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v5

  #     # Set up .NET
  #     - name: Set up .NET
  #       uses: actions/setup-dotnet@v5
  #       with:
  #         dotnet-version: 10.x

  #     # Restore .NET tools
  #     - name: Restore .NET dependencies
  #       run: dotnet tool restore

  #     # Install Node.js
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 22
  #         cache: "npm"

  #     # Install npm dependencies
  #     - name: Install root npm dependencies
  #       run: npm i

  #     # Install playwright dependencies
  #     - name: Install Playwright dependencies
  #       working-directory: src/Components
  #       run: npx playwright install --with-deps chromium

  #     - name: Run Tests
  #       run: dotnet run --project ./build/Build.fsproj test

  # --- Job 2: Create release ---
  release:
    # needs: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      # Restore .NET tools
      - name: Restore .NET dependencies
        run: dotnet tool restore

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      # Install npm dependencies
      - name: Install root dependencies
        run: npm i

      # publish swate-app
      - name: Publish swate-app
        working-directory: src/Electron
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
