name: Run Tests

on:
  pull_request: # Triggers on pull requests
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      # Restore .NET tools
      - name: Restore .NET dependencies
        run: dotnet tool restore

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      # Trusted publishing with npm requires at least npm version 11.5.1, BUT node v22 comes with npm v10.x.
      # https://docs.npmjs.com/trusted-publishers
      - name: Update npm version to at least 11.5.1
        run: npm install -g npm@11.5.1

      # Install npm dependencies
      - name: Install root npm dependencies
        run: npm i

      # Install playwright dependencies
      - name: Install Playwright dependencies
        working-directory: src/Components
        run: npx playwright install --with-deps chromium

      - name: Test Restore
        run: dotnet restore ./Swate.sln

      - name: Test Build
        run: dotnet build ./Swate.sln

      - name: Run Tests
        run: dotnet run --project ./build/Build.fsproj -- test
